prog:AffichageObj.o  main.o
	gcc AffichageObj.o  main.o -o prog -lSDL -lSDL_image -lSDL_mixer -g


AffichageObj.o:AffichageObj.c
	gcc -c AffichageObj.c -lSDL -lSDL_image -g

main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -g



