prog:afficher.o main7.o initialiser.o coll.o 
	gcc afficher.o main7.o initialiser.o coll.o -o prog -lSDL -lSDL_image -g
main7.o:main7.c
	gcc -c main7.c -lSDL -lSDL_image -g
inisialiser.o:inisialiser.c
	gcc -c inisialiser.c -lSDL -lSDL_image -g
afficher.o:afficher.c
	gcc -c afficher.c -lSDL -lSDL_image -g
coll.o:coll.c
	gcc -c coll.c -lSDL -lSDL_image -g
