prog: i.o n.o v.o main5.o main2.o personne.o main.o f.o
	gcc  i.o n.o v.o main5.o main2.o personne.o main.o f.o -o prog -lSDL -lSDL_image -g

i.o:i.c
	gcc -c i.c -lSDL -lSDL_image -g
n.o:n.c
	gcc -c n.c -lSDL -lSDL_image -g
v.o:v.c
	gcc -c v.c -lSDL -lSDL_image -g
main5.o:main5.c
	gcc -c main5.c -lSDL -lSDL_image -g
main2.o:main2.c
gcc -c main2.c -lSDL -lSDL_image -g
f.o:f.c
gcc -c f.c -lSDL -lSDL_image -g
personne.o:personne.c
gcc -c personne.c -lSDL -lSDL_image -g

main.o:main.c
gcc -c main.c -lSDL -lSDL_image -
